:_mod-docs-content-type: PROCEDURE
[id="nw-viewing-service-l2-status_{context}"]
= Viewing ServiceL2Status

[role="_abstract"]
You can verify which node is advertising your service in Layer 2 mode by checking the ServiceL2Status custom resource. This helps you troubleshoot L2 advertisement issues and confirm the expected announcer node.

The ServiceL2Status CR provides details about which node is advertising a service using Layer 2 mode. This is useful for troubleshooting to confirm that the correct node is acting as the announcer.

.Prerequisites

* You have an {product-title} cluster with the MetalLB Operator installed.
* You have at least one MetalLB Custom Resource (CR) instance created.

.Procedure

. View the status of the ServiceL2Status CR by running the following command:
+
[source,terminal]
----
$ oc get ServiceL2Status -n metallb-system
----
+
The output is similar to the following:
+
[source,terminal]
----
NAME                    LABELS                                                   AGE
nginx-service-worker0   metallb.io/node=worker0,metallb.io/service=nginx-service 5h
----

. View the details of the ServiceL2Status CR for your service:
+
[source,terminal]
----
$ oc get servicel2status nginx-service-worker0 -n metallb-system -o yaml
----
+
The output is similar to the following:
+
[source,yaml]
----
apiVersion: metallb.io/v1beta1
kind: ServiceL2Status
metadata:
  name: nginx-service-worker0
  namespace: metallb-system
  labels:
    metallb.io/node: worker0
    metallb.io/service: nginx-service
spec: {}
status:
    node: worker0
    interfaces:
        - eth0

----
+
The output includes the following important fields:
+
* `metadata.labels.metallb.io/node` identifies the node that is advertising the service. This is useful for troubleshooting to verify which node is the announcer.
* `metadata.labels.metallb.io/service` identifies the service that is being advertised.
* `status.node` confirms the name of the node advertising the service.
* `status.interfaces` lists the network interfaces on the announcing node that are used for the advertisement. If the field is empty, all interfaces on the node are being used for the advertisement.